/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Aozora RAG API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  BodyUploadFile,
  ChatInput,
  ChatOutput,
  HTTPValidationError,
  UploadResponse,
} from "./model";

/**
 * @summary Chat Endpoint
 */
export const chatEndpointChatPost = (
  chatInput: ChatInput,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ChatOutput>> => {
  return axios.default.post(`http://localhost:8005/chat/`, chatInput, options);
};

export const getChatEndpointChatPostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatEndpointChatPost>>,
    TError,
    { data: ChatInput },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatEndpointChatPost>>,
  TError,
  { data: ChatInput },
  TContext
> => {
  const mutationKey = ["chatEndpointChatPost"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatEndpointChatPost>>,
    { data: ChatInput }
  > = (props) => {
    const { data } = props ?? {};

    return chatEndpointChatPost(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatEndpointChatPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatEndpointChatPost>>
>;
export type ChatEndpointChatPostMutationBody = ChatInput;
export type ChatEndpointChatPostMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Chat Endpoint
 */
export const useChatEndpointChatPost = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chatEndpointChatPost>>,
      TError,
      { data: ChatInput },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof chatEndpointChatPost>>,
  TError,
  { data: ChatInput },
  TContext
> => {
  const mutationOptions = getChatEndpointChatPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * ファイルをアップロードし、ドキュメントとして処理します。

- **file**: アップロードするファイル
- **title**: ユーザーが指定するタイトル
 * @summary Upload File
 */
export const uploadFile = (
  bodyUploadFile: BodyUploadFile,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UploadResponse>> => {
  const formData = new FormData();
  formData.append(`file`, bodyUploadFile.file);
  formData.append(`title`, bodyUploadFile.title);

  return axios.default.post(`http://localhost:8005/upload`, formData, options);
};

export const getUploadFileMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadFile>>,
    TError,
    { data: BodyUploadFile },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadFile>>,
  TError,
  { data: BodyUploadFile },
  TContext
> => {
  const mutationKey = ["uploadFile"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadFile>>,
    { data: BodyUploadFile }
  > = (props) => {
    const { data } = props ?? {};

    return uploadFile(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadFile>>
>;
export type UploadFileMutationBody = BodyUploadFile;
export type UploadFileMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Upload File
 */
export const useUploadFile = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadFile>>,
      TError,
      { data: BodyUploadFile },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadFile>>,
  TError,
  { data: BodyUploadFile },
  TContext
> => {
  const mutationOptions = getUploadFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
