/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Aozora RAG API
 * OpenAPI spec version: 0.1.0
 */
import type { SourceItem } from "./sourceItem";

export type AnswerItemsSources = SourceItem[] | null;
