/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Aozora RAG API
 * OpenAPI spec version: 0.1.0
 */
import type { ChatOutputResponses } from "./chatOutputResponses";

/**
 * チャットボットの出力データの仕様書
 */
export interface ChatOutput {
  responses?: ChatOutputResponses;
}
