/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Aozora RAG API
 * OpenAPI spec version: 0.1.0
 */
import type { SourceItemTitle } from "./sourceItemTitle";
import type { SourceItemPage } from "./sourceItemPage";

export interface SourceItem {
  title?: SourceItemTitle;
  url: string;
  page?: SourceItemPage;
}
