/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Aozora RAG API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Chat Endpoint
 */
export const chatEndpointChatPostBodyQuestionsMaxOne = 10;



export const chatEndpointChatPostBody = zod.object({
  "questions": zod.union([zod.array(zod.string()).min(1).max(chatEndpointChatPostBodyQuestionsMaxOne),zod.null()]).optional()
})

export const chatEndpointChatPostResponse = zod.object({
  "responses": zod.union([zod.array(zod.object({
  "response": zod.string(),
  "sources": zod.union([zod.array(zod.object({
  "title": zod.string(),
  "url": zod.string()
})),zod.null()]).optional()
})),zod.null()]).optional()
}).describe('チャットボットの出力データの仕様書')
