/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Aozora RAG API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Chat Endpoint
 */
export const chatEndpointChatPostBodyQuestionsMaxOne = 10;



export const chatEndpointChatPostBody = zod.object({
  "questions": zod.union([zod.array(zod.string()).min(1).max(chatEndpointChatPostBodyQuestionsMaxOne),zod.null()]).optional()
})

export const chatEndpointChatPostResponse = zod.object({
  "responses": zod.union([zod.array(zod.object({
  "question": zod.string(),
  "answer": zod.string(),
  "sources": zod.union([zod.array(zod.object({
  "title": zod.union([zod.string(),zod.null()]).optional(),
  "url": zod.string(),
  "page": zod.union([zod.number(),zod.null()]).optional()
})),zod.null()]).optional()
})),zod.null()]).optional()
}).describe('チャットボットの出力データの仕様書')


/**
 * ファイルをアップロードし、ドキュメントとして処理します。

- **file**: アップロードするファイル
- **title**: ユーザーが指定するタイトル
 * @summary Upload File
 */
export const uploadFileBody = zod.object({
  "file": zod.instanceof(File),
  "title": zod.string()
})

export const uploadFileResponse = zod.object({
  "message": zod.string(),
  "processed_pages": zod.number()
})
